### ISSUE TITLE
Some features I am missing

### ISSUE THREAD

**Issue by Luukiemajo** [PrimeGamesDevTeam/issues-feedbacks#1]
Skyblock V2

The problem is that selling items in the shop takes too long.

The easiest solution would be an additional option to sell, like the /sell all or /sa command

A different solution for this problem would be to change the shop from a 128 blocks each time to a shop where we can enter the ammount of block we want to buy/sell ourselves 

![Screenshot_20200720-091157_Minecraft](https://user-images.githubusercontent.com/68533642/87910486-6484f280-ca6a-11ea-8dd4-1606ae660b1c.jpg)
^this is annoying

**Comment by ver24436** [comment]
I agree the current process to sell is tedious, just trying to sell an inventory of cactus takes 162 taps/clicks. No one wants to spend this much time just trying to sell items.

**Comment by FatihAtlamaz** [comment]
For buying bulks of items, maybe add a command such as /buy (item) (amount). For example, /buy dirt 256.
