### ISSUE TITLE
SurvivalV2 Land Sell

### ISSUE THREAD

**Issue by SpicyAir** [PrimeGamesDevTeam/issues-feedbacks#16]
SurvivalV2

If you decide to sell land you've claimed, you don't get any money back. This is not a major issue, but it can be frustrating to some people.

Have it so when a player gets rid of a piece of land, it gives them 40%-60% of the amount of money it would've cost to claim the land.

**Comment by Rushil13579** [comment]
Players will now receive a 50% return on selling their land.
