### ISSUE TITLE
SurvivalV2 Repair Costs

### ISSUE THREAD

**Issue by SpicyAir** [PrimeGamesDevTeam/issues-feedbacks#19]
SurvivalV2

Right now, repair costs scale up exponentially. A pickaxe might cost 6/7 lvls to repair at first, then go up to 15-35-60-85 (just an example, not exact costs). This is too much imo, you are pretty much forced to make new pickaxes after like 2 or 3 repairs. If you try to use all 5 repairs for a pickaxe, you'll end up spending hundreds of lvls on 1 pickaxe and eventually you can't repair it and you don't have enough lvls to make another good pick

XP costs could be lowered to like +5 levels or something around x1.60 for every repair.

XP could also be made easier to grind. There are a variety of ways to do this but some ideas include:

-Buffing ores xp output (?)
-Adding a new source of xp like mobs
-Making Experience ce cheaper and more accessible

**Comment by nasiridrishi** [comment]
That is intentional
