### ISSUE TITLE
SurvivalV2 Provide crafting materials for enderchest crafting

### ISSUE THREAD

**Issue by SpicyAir** [PrimeGamesDevTeam/issues-feedbacks#21]
SurvivalV2

There are no ender chests. This means there is a lack of easy access storage for players and no way for new players who haven't got land to safely store valuables.

Add the item to the shop for something like 3000 each.

The price could vary. Another option is to add blaze rods to the shop so players could craft them. This would not work quite as well as the ender chests would be very cheap but is still an option.

**Comment by SathvikGunda** [comment]
I believe survival spawn has an embedded enderchest.

**Comment by SpicyAir** [comment]
> I believe survival spawn has an embedded enderchest.

It used to have one, but you couldn't open it. Whenever the latest update was rolled out, the map was updated and the ender chest doesn't even exist anymore.

**Comment by SathvikGunda** [comment]
Update the map with new enderchest again.@SpicyAir

**Comment by OmChendvankar** [comment]
left click, right click actions are disabled at spawn

**Comment by nasiridrishi** [comment]
players must find/buy items required to buy enderchest

**Comment by Rushil13579** [comment]
Resolved.
