### ISSUE TITLE
KitPvp - Streak system

### ISSUE THREAD

**Issue by siloonk** [PrimeGamesDevTeam/issues-feedbacks#24]
KitPvp
**Is your feature request related to a problem? Please describe.**
My feature is related to the issue where you lose your streak when you leave the server, This is a very unliked feature in the kit-pvp community.

I would like your streak to stay after you log off (Only if you arent in combat of course)

**Comment by SathvikGunda** [comment]
Are you trying to say that you want to keep your streak even after logging off? And continue raising It only u till you die or combat log?

**Comment by siloonk** [comment]
> Are you trying to say that you want to keep your streak even after logging off? And continue raising It only u till you die or combat log?

Yes

**Comment by nasiridrishi** [comment]
We have discussed about it in discord server many times, this is a streak rule which applied on everyone so it is fair and it will stay this way, although, we will add way so player does not loose streak if server reboots.
