### ISSUE TITLE
Discord Booster Perks

### ISSUE THREAD

**Issue by SpicyAir** [PrimeGamesDevTeam/issues-feedbacks#25]
Discord

Currently, there are basically no perks for boosting the discord server. All you get is a role that may or may not change your name color

Add some perks for boosting the server. Possible ideas:

-Server Boosters given a cosmetic in-game role called Booster in pink.
-Server Boosters given access to a special channel that only boosters and staff can access. -Server Boosters are allowed to have 1 account that is verified on their discord profile be given a temporary Poseidon rank in-game as long as they are boosting.
-A new account that boosts the server is allowed to apply for a 25% discount code for the PG Store after being a booster for at least 30 days.
-More permissions in PG Discord (Reacting to messages, separate display area under staff members, etc)

**Comment by SathvikGunda** [comment]
Not a good idea as of now because of discord giving free nitro for 3 months, maybe later after everyone runs out of the free nitro.

**Comment by SpicyAir** [comment]
> Not a good idea as of now because of discord giving free nitro for 3 months, maybe later after everyone runs out of the free nitro.

That's a fair point. I think some perks should be added eventually tho. Most mc servers have some sort of perk for server boosting and rn PG has none.

**Comment by nasiridrishi** [comment]
We use git issues for in game issues, task etc. Not for discord
